### ISSUE TITLE
Change name of tracking functions

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-fac/pyaccel#28]

**Comment by xresende** [comment]
I do not remember what is the idea here. Has this been done already? @LuanaVilela @afonsoharuo

**Comment by xresende** [comment]
since we abandoned keeping pyaccel close to AT we can change the function name convention: we will use underscore to separate words.

**Comment by afonsoharuo** [comment]
Changed names, but kept old function names as a legacy interface. Added deprecation warnings to old function calls.
