### ISSUE TITLE
strange behavior of slicing for the_ring

### ISSUE THREAD

**Issue by xresende** [lnls-fac/pyaccel#29]
These two codes generate different results:

```Python
for i in range(len(the_ring)):
  e = the_ring[i]
  e.hmax = 0.012
```

```Python
for e in the_ring:
  e.hmax = 0.012
```

**Comment by afonsoharuo** [comment]
What are the different results? I could not find the difference.

**Comment by afonsoharuo** [comment]
Object was of CppElementVector type; we can use the first syntax, which works as intended.
