### ISSUE TITLE
Comparison of accelerators

### ISSUE THREAD

**Issue by fernandohds564** [lnls-fac/pyaccel#35]
I would like to compare two accelerators for equality. This could be achieved easily, according to this reference http://stackoverflow.com/questions/25087232/python-swig-object-compare , if the objects in C++ have this functionality implemented. But it seems the accelerator in C++ is only a structure. Is it correct, @xresende?
Even if this is the case, we could break the comparison of accelerators in a loop over its elements and compare each one to another. This would imply having the equality operation implemented for the class Element in C++. Is it difficult to do, @xresende ?
It is possible to compare elements in python by looking at every property, but, as properties do not appear in the *\_\_dict\_\_* of the element, the code would be very ugly and less reliable.

Another desired, but less important, functionality is the proper function of the python operator __is__. Currently this happens:

    >> acc = sirius.SI_V10.create_accelerator()
    >> acc2 = acc
    >> acc2 is acc, acc2._accelerator is acc._accelerator, 
    True, True

which is the expected result. However:

    >> acc2._accelerator.lattice is acc._accelerator.lattice, acc2[1].length is acc[1].length
    False, False
    >> acc2[1].length = 100000
    >> acc[1].length
    100000.0

which means they are the same object but the **is** operator does not see it.
 @afonsoharuo @LuanaVilela

**Comment by fernandohds564** [comment]
I implemented the comparison in python, but it is very slow. It takes about 2 seconds to compare two sirius lattices when they are equal.

**Comment by xresende** [comment]
At _trackcpp_ the accelerator is a simple structure, as you said, @fernandohds564 . But its field _lattice_ is a vector of _Element_ class objects. It should not be too difficult to implement an accelerator comparison at _trackcpp_. This function can easily be exported to python through swig. Certainly it will be much faster than the python comparison. I'll do it.

**Comment by afonsoharuo** [comment]
@xresende implemented it.

**Comment by fernandohds564** [comment]
@xresende I still can't compare the accelerators. I get an error pointing to the inexistence of the attribute *isequal*.

**Comment by fernandohds564** [comment]
It worked! I am not sure what I did, but I applied a bunch of make clean and uninstall of the packages. :). I'll try to reproduce it at work and annotate the procedure here.

**Comment by xresende** [comment]
:thumbsup:
