### ISSUE TITLE
Consistency of indices in tracking.findm66

### ISSUE THREAD

**Issue by fernandohds564** [lnls-fac/pyaccel#39]
At least it seems a bug for me. What do you guys think, @xresende @afonsoharuo @LuanaVilela ?

The length of *_m66*, returned from trackcpp, should be **len(accel)+1**, because it should have the cumulated transfer matrix at the exit of the last element. However, its length is only **len(accel)**. Currently we take the last element of this list as the one turn matrix, which generates correct results for most cases, because usually the last element is a marker, but is not correct in general.

**Comment by afonsoharuo** [comment]
The values in pyaccel are given for the end of the element at that index; e.g.
```
m66, cm = findm66(a)
# cm[2] is the value at the end of a[2]
```
So the last value is the right one for m66.

Added that to the documentation for now, but we have to evaluate it for consistency. Other functions, such as find_spos, return values at the start of each element.

**Comment by fernandohds564** [comment]
Thank you @afonsoharuo . That's very important!. 
So all the twiss parameters are also calculated at the end of the elements? This response is different from AT, isn't it? is that what we want?

**Comment by afonsoharuo** [comment]
Twiss parameters are also returned at start of elements. The case of transfer matrices is different, as the transfer matrix from the start of the lattice to the start of the first element will always be the identity matrix.

AT's findm66 returns the matrices at the start of each element, but only when called with two input arguments, the second being the indices of the elements where the values are wanted.

**Comment by fernandohds564** [comment]
What are the advantages of this property of findm66? Because it seems all the other methods, and AT, follow a different convention.

**Comment by afonsoharuo** [comment]
Changed findm66 and findm44. Now values are at the start of each lattice element.
