### ISSUE TITLE
On the impossibility of setting a section of an accelerator object with other accelerator

### ISSUE THREAD

**Issue by fernandohds564** [lnls-fac/pyaccel#40]
Guys, I tried this:

    >>> acc = sirius.SI_V10.create_accelerator()
    >>> a = [1,2,3,4,5,6,7,8]
    >>> acc2 = acc[a]
    >>> acc2[0].fam_name = 'bla'
    >>> acc[1].fam_name
    'mia'
    >>> #up to here everything ok, or at least as I expected. But then:
    >>> acc[a] = acc2

but I got an error after the last command. Do we really want this behavior? currently we cannot set parts of an accelerator with other accelerator, but this could be very handy. For example, we do this in the orbit correction algorithm in matlab to keep track of the best setting of correctors and apply them to the accelerator model in the end. Do I have your permission implement this funcionality, @xresende, @afonsoharuo and @LuanaVilela ?

**Comment by fernandohds564** [comment]
I noticed the syntax of *__setitem__* allowed setting of parts of an accelerator object with a list or a tuple of Element objects, then I concluded this was a bug and not a lack of feature of the code. So I corrected it. If you all agree, I will close the issue.

**Comment by afonsoharuo** [comment]
Agreed. I corrected another bug, concerning __setitem__ with slices.
