### ISSUE TITLE
Add wrapper class to CppMatrixVector

### ISSUE THREAD

**Issue by afonsoharuo** [lnls-fac/pyaccel#43]
So that we can use it as a Python object in pyaccel and avoid the time consuming conversion of the transfer matrix vector returned from trackcpp's findm66.

**Comment by afonsoharuo** [comment]
Added a read-only matrix list class. Do we need to be able to change elements of matrices?

**Comment by fernandohds564** [comment]
:+1:
I don't think so. Actually it is a good thing not being able to change them. :smile:
