### ISSUE TITLE
Add possibility for saving and reading accelerator to and from files

### ISSUE THREAD

**Issue by xresende** [lnls-fac/pyaccel#9]
We should stick to flat_file format already used by AT/trackcpp

**Comment by afonsoharuo** [comment]
In the case of dipoles, not all fields are being written to file, when they are zero or default (identity rotation matrix, for example). Is it necessary to write all of them?

**Comment by xresende** [comment]
I think it is ok: not necessary to write them all to file, as long as the value to these parameters are equal default values...
